spring:
  datasource:
    url: jdbc:mysql:///ssm?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: luo123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
#  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
management:
  endpoints:
    enabled-by-default: true #暴露所有端点信息
    web:
      exposure:
        include: '*'  #以web方式暴露